[package]
name = "rustfx"
version = "0.1.0"
authors = ["cyril"]
links = "ofxhelpers"
build = "build.rs"

[profile.dev]
panic = 'abort'
debug = true 

[dependencies]
libc = "*"
log = "0.3"
env_logger = "0.3"

[build-dependencies]
gcc = "0.3"

