

# Only works on MacOS for now
all:OFX/basic.ofx.bundle/Contents/MacOS-x86-64/basic.ofx OFX/custom.ofx.bundle/Contents/MacOS-x86-64/custom.ofx OFX/invert.ofx.bundle/Contents/MacOS-x86-64/invert.ofx OFX/rectangle.ofx.bundle/Contents/MacOS-x86-64/rectangle.ofx

OFX/rectangle.ofx.bundle/Contents/MacOS-x86-64/rectangle.ofx: rectangle.o
	g++ -bundle rectangle.o -o rectangle.ofx
	mkdir -p OFX/rectangle.ofx.bundle/Contents/MacOS-x86-64/
	mv rectangle.ofx $@ 

rectangle.o: rectangle.cpp ofxUtilities.hpp
	g++ -c -g -fvisibility=hidden -fPIC -I../../src/include rectangle.cpp -o rectangle.o

OFX/basic.ofx.bundle/Contents/MacOS-x86-64/basic.ofx: basic.o
	g++ -bundle basic.o -o basic.ofx
	mkdir -p OFX/basic.ofx.bundle/Contents/MacOS-x86-64/
	mv basic.ofx $@ 

basic.o: basic.cpp ofxUtilities.hpp
	g++ -c -g -fvisibility=hidden -fPIC -I../../src/include basic.cpp -o basic.o

OFX/custom.ofx.bundle/Contents/MacOS-x86-64/custom.ofx: custom.o
	g++ -bundle -framework OpenGL custom.o -o custom.ofx
	mkdir -p OFX/custom.ofx.bundle/Contents/MacOS-x86-64/
	mv custom.ofx $@ 

custom.o: custom.cpp ofxUtilities.hpp
	g++ -c -g -fvisibility=hidden -fPIC -I../../src/include custom.cpp -o custom.o

OFX/invert.ofx.bundle/Contents/MacOS-x86-64/invert.ofx: invert.o
	g++ -bundle -framework OpenGL invert.o -o invert.ofx
	mkdir -p OFX/invert.ofx.bundle/Contents/MacOS-x86-64/
	mv invert.ofx $@ 

invert.o: invert.cpp ofxUtilities.hpp
	g++ -c -g -fvisibility=hidden -fPIC -I../../src/ofx invert.cpp -o invert.o

clean: 
	rm *.o
